/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Complaint {
  'status' : ComplaintStatus,
  'applicantName' : string,
  'submissionTimestamp' : Time,
  'complaintDetail' : string,
  'mobileNumber' : string,
  'notificationLog' : Array<Notification>,
  'complaintNumber' : bigint,
  'attachedFile' : [] | [ExternalBlob],
  'fatherName' : string,
  'address' : string,
  'assignedOfficerId' : [] | [string],
}
export type ComplaintStatus = { 'resolved' : null } |
  { 'pending' : null } |
  { 'inProgress' : null };
export type ExternalBlob = Uint8Array;
export interface Notification { 'message' : string, 'timestamp' : Time }
export interface Officer {
  'officerId' : string,
  'name' : string,
  'designation' : string,
  'mobileNumber' : string,
}
export type Time = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addOfficer' : ActorMethod<[string, string, string, string], undefined>,
  'assignOfficer' : ActorMethod<[bigint, string], undefined>,
  'getComplaint' : ActorMethod<[bigint], Complaint>,
  'listComplaints' : ActorMethod<[[] | [ComplaintStatus]], Array<Complaint>>,
  'listOfficers' : ActorMethod<[], Array<Officer>>,
  'submitComplaint' : ActorMethod<
    [string, string, string, string, string, [] | [ExternalBlob]],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];