/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ComplaintStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Time = IDL.Int;
export const AttendanceLog = IDL.Record({
  'attendanceDate' : IDL.Text,
  'attendanceTime' : IDL.Text,
  'attendedBy' : IDL.Text,
  'remarks' : IDL.Opt(IDL.Text),
});
export const StatusLogEntry = IDL.Record({
  'status' : ComplaintStatus,
  'updatedAt' : Time,
  'updatedBy' : IDL.Text,
  'details' : IDL.Text,
});
export const Notification = IDL.Record({
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Complaint = IDL.Record({
  'status' : ComplaintStatus,
  'applicantName' : IDL.Text,
  'submissionTimestamp' : Time,
  'complaintDetail' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'attendanceLog' : IDL.Vec(AttendanceLog),
  'statusLog' : IDL.Vec(StatusLogEntry),
  'notificationLog' : IDL.Vec(Notification),
  'complaintNumber' : IDL.Nat,
  'attachedFile' : IDL.Opt(ExternalBlob),
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'assignedOfficerId' : IDL.Opt(IDL.Text),
});
export const Officer = IDL.Record({
  'officerId' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'mobileNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addOfficer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignOfficer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComplaint' : IDL.Func([IDL.Nat], [Complaint], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listComplaints' : IDL.Func(
      [IDL.Opt(ComplaintStatus)],
      [IDL.Vec(Complaint)],
      ['query'],
    ),
  'listOfficers' : IDL.Func([], [IDL.Vec(Officer)], ['query']),
  'recordAttendance' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitComplaint' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Nat],
      [],
    ),
  'updateComplaintStatus' : IDL.Func(
      [IDL.Nat, ComplaintStatus, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ComplaintStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Time = IDL.Int;
  const AttendanceLog = IDL.Record({
    'attendanceDate' : IDL.Text,
    'attendanceTime' : IDL.Text,
    'attendedBy' : IDL.Text,
    'remarks' : IDL.Opt(IDL.Text),
  });
  const StatusLogEntry = IDL.Record({
    'status' : ComplaintStatus,
    'updatedAt' : Time,
    'updatedBy' : IDL.Text,
    'details' : IDL.Text,
  });
  const Notification = IDL.Record({ 'message' : IDL.Text, 'timestamp' : Time });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Complaint = IDL.Record({
    'status' : ComplaintStatus,
    'applicantName' : IDL.Text,
    'submissionTimestamp' : Time,
    'complaintDetail' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'attendanceLog' : IDL.Vec(AttendanceLog),
    'statusLog' : IDL.Vec(StatusLogEntry),
    'notificationLog' : IDL.Vec(Notification),
    'complaintNumber' : IDL.Nat,
    'attachedFile' : IDL.Opt(ExternalBlob),
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'assignedOfficerId' : IDL.Opt(IDL.Text),
  });
  const Officer = IDL.Record({
    'officerId' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'mobileNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addOfficer' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignOfficer' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComplaint' : IDL.Func([IDL.Nat], [Complaint], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listComplaints' : IDL.Func(
        [IDL.Opt(ComplaintStatus)],
        [IDL.Vec(Complaint)],
        ['query'],
      ),
    'listOfficers' : IDL.Func([], [IDL.Vec(Officer)], ['query']),
    'recordAttendance' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitComplaint' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Nat],
        [],
      ),
    'updateComplaintStatus' : IDL.Func(
        [IDL.Nat, ComplaintStatus, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };